services:
  redis:
    container_name: service_redis
    image: redis:8.4
    networks:
      - redis_network
    volumes:
      - service_logs:/logs
  website:
    container_name: service_website
    build: ./containers/services/website
    restart: on-failure
    volumes:
      - website_data:/var/www/website
      - service_logs:/logs
    depends_on:
      - api
    ports:
      - 5173:5173
    networks:
      - website_network
  api:
    container_name: service_api
    build: ./containers/services/api
    restart: on-failure
    env_file:
      - env/api.env
    volumes:
      - api_data:/var/www/api
      - service_logs:/logs
    ports:
      - 5050:5050
    networks:
      - auth_network
      - website_network
      - game_network
      - redis_network
      - user_db_network
  auth:
    container_name: service_auth
    build: ./containers/services/auth
    restart: on-failure
    env_file:
      - env/auth.env
    depends_on:
      - auth_db
    volumes:
      - service_logs:/logs
    networks:
      - auth_network
      - redis_network
      - auth_db_network
  game:
    container_name: service_game
    build: ./containers/services/game
    restart: on-failure
    volumes:
      - service_logs:/logs
    networks:
      - game_network
  lobby:
    container_name: lobby_game
    build: ./containers/services/lobby
    restart: on-failure
    ports:
      - "5002:5002"
    env_file:
      - env/lobby.env
    networks:
      - lobby_network
      - redis_network
      - user_db_network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    env_file:
      - env/elasticsearch.env
    ports:
      - "5065:9200"
    networks:
      - elk_network
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk_network
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.0
    user: root
    volumes:
      - service_logs:/logs
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elasticsearch
    networks:
      - elk_network
  auth_db:
    container_name: auth_db
    build: ./containers/databases/auth_db
    restart: unless-stopped
    env_file:
      - env/auth_db.env
    volumes:
      - auth_db_data:/var/lib/mysql
      - service_logs:/logs
    networks:
      - auth_db_network
  user_db:
    container_name: user_db
    build: ./containers/databases/user_db
    restart: unless-stopped
    env_file:
      - env/user_db.env
    volumes:
      - user_db_data:/var/lib/mysql
      - service_logs:/logs
    networks:
      - user_db_network

volumes:
  website_data:
  api_data:
  auth_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/auth_db_volume
  user_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/user_db_volume
  service_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/service_logs


networks:
  mariadb_network:
    driver: bridge
  auth_network:
    driver: bridge
  game_network:
    driver: bridge
  website_network:
    driver: bridge
  auth_db_network:
    driver: bridge
  user_db_network:
    driver: bridge
  redis_network:
    driver: bridge
  lobby_network:
    driver: bridge
  elk_network:
    driver: bridge
