input {
  file {
    path => "/logs/*.log"
    start_position => "beginning"
    codec => json
  }
}

filter {
  # Add any required parsing here if the logs require further formatting.
  # The JSON codec usually unrolls JSON objects automatically.
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    # Depending on requirements, we can name the index pattern
    # index => "logstash-%{+YYYY.MM.dd}"
  }
}
