CREATE DATABASE IF NOT EXISTS user_obj_links
	CHARACTER SET utf8mb4
	COLLATE utf8mb4_unicode_ci;

use user_obj_links;

CREATE TABLE card_gallery (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	user_id BIGINT UNSIGNED NOT NULL,
	img_url VARCHAR(255) NOT NULL,
) ENGINE=InnoDB;
