import { CardFamily, CardsTheme } from "../domain/GameEnums";

export const GAME_CUSTOMIZATION = {
	app: {
		backgroundColor: "#291c3d",
		socketUrl: "http://localhost:3000",
		socketTransports: ["websocket"],
		canvasAspectRatio: 16 / 9,
		defaultTheme: CardsTheme.Basic,
		defaultCardBackVariants: ["uwu"],
	},
	assets: {
		arrowTexturePath: "arrow.png",
		cardBackFileSuffix: "-back.png",
		defaultCardBackVariant: "default",
		themeFileByTheme: {
			[CardsTheme.Basic]: "basic-theme.json",
			[CardsTheme.Uwu]: "uwu-theme.json",
		},
	},
	table: {
		middleArrowYRatio: 0.43,
		middleArrowSizeFromCenterAreaRatio: 0.12,
		unoButtonYRatio: 0.57,
		unoButtonWidthRatio: 0.08,
		turnTimer: {
			durationMs: 10000,
			heightRatio: 0.012,
			minHeightPx: 6,
			offsetYRatio: 0.02,
			cornerRadiusRatio: 0.5,
			backgroundColor: "#000000",
			backgroundAlpha: 0.45,
			fillColor: "#7a00b2",
		},
		playerHandYRatio: 0.875,
		pilesOffsetDivisor: 9,
		cardFamilySelectorRadiusRatio: 0.18,
		pilesFallbackGrey: "#9a9a9a",
		defaultRejoinCardBackVariant: "uwu",
		playerHand: {
			areaPercent: 0.7,
			overlapPercent: 0.4,
			cardRatio: 0.66,
		},
		unoButton: {
			baseWidth: 96,
			aspectRatio: 16 / 9,
			fillColor: "#291c3d",
			labelFontSize: 26,
			cornerRadiusRatio: 0.16,
			strokeWidth: 5,
			strokeColor: 0xffffff,
			labelFillColor: 0xffffff,
			fontCssVariable: "--font-pixelm",
			fontFallback: "PixelHB",
		},
	},
	centerArea: {
		mainWidthRatio: 0.35,
		mainAspectRatio: 8 / 16,
		mainBorderDarken: 0.12,
		mainCornerRadiusRatio: 0.12,
		mainStrokeWidth: 2,
		backdropWidthRatio: 0.13,
		backdropAspectRatio: 11 / 16,
		backdropCornerRadiusRatio: 0.18,
		backdropFillAlpha: 0.18,
		backdropStrokeWidth: 2,
		deckDiscardOffsetDivisor: 9,
		borderRadiusExtra: 4,
		defaultMainColor: "#3e295d",
		defaultBackdropColor: "#470068",
		defaultCenterBorderColor: "#470068",
		centerBorderThickness: 6,
		fallbackFamilyColor: "#9a9a9a",
		defaultFamilyColors: {
			[CardFamily.ONE]: "#2c7fe5",
			[CardFamily.TWO]: "#26cd00",
			[CardFamily.THREE]: "#ff1249",
			[CardFamily.FOUR]: "#ffc412",
			[CardFamily.WILD]: "#9a9a9a",
		},
	},
	opponents: {
		hand: {
			areaPercent: 0.7,
			overlapPercent: 0.4,
			cardRatio: 0.66,
		},
		positions: {
			topYRatio: 0.125,
			leftXRatio: 0.07,
			rightXRatio: 0.93,
		},
		names: {
			fontSizeRatio: 0.025,
			minFontSizePx: 12,
			maxFontSizePx: 32,
			fillColor: 0xffffff,
			fontCssVariable: "--font-pixelm",
			fontFallback: "PixelHB",
			alpha: 0.9,
			topCenterBias: 0.3,
			sideCenterBias: 0.4,
			picture: {
				sizeRatio: 0.08,
				minSizePx: 24,
				maxSizePx: 64,
				spacing: 8,
				cornerRadiusRatio: 0.15,
			},
		},
		defaultRejoinCardBackVariant: "uwu",
	},
	selector: {
		defaultRadius: 90,
		borderColor: 0x2f2f2f,
		borderAlpha: 0.95,
		borderWidth: 4,
		pixelSize: 3,
		minArcSteps: 6,
	},
	victory: {
		labels: {
			defaultButton: "HOME",
			victory: "VICTORY",
			defeat: "DEFEAT",
			tablePlayerHeader: "PLAYER",
			tableCardsHeader: "CARDS LEFT",
			homePath: "/",
		},
		ratios: {
			panelWidth: 0.76,
			panelAspect: 16 / 9,
			panelCornerRadius: 0.03,
			titleTop: 0.06,
			statsTop: 0.24,
			tableTop: 0.38,
			tableHeight: 0.36,
			tableSidePadding: 0.12,
			tableHeaderFont: 0.032,
			tableRowFont: 0.03,
			tableHeaderToRowsGap: 0.2,
			tableRowExtraGap: 0.15,
			buttonBottom: 0.1,
			titleFont: 0.07,
			statsFont: 0.032,
			buttonWidth: 0.32,
			buttonHeight: 0.12,
			buttonCornerRadius: 0.2,
			buttonLabelFont: 0.36,
		},
		colors: {
			overlay: 0x0f0820,
			panel: 0x2b1e44,
			panelStroke: 0xffffff,
			titleText: 0xffffff,
			statsText: 0xd5cfff,
			buttonFill: 0xc63845,
			buttonStroke: 0xffffff,
			buttonLabelText: 0xffffff,
		},
		alphas: {
			overlay: 0.7,
			panel: 0.97,
			panelStroke: 0.2,
			buttonStroke: 0.8,
			buttonPressed: 0.82,
		},
		sizes: {
			panelStrokeWidth: 3,
			buttonStrokeWidth: 3,
			titleFontPx: 56,
			statsFontPx: 19,
			buttonFontPx: 24,
		},
		buttonPressedScale: 0.95,
		buttonAnimationDurationMs: 130,
		fontCssVariable: "--font-pixelm",
		fontFallback: "PixelHB",
	},
	hand: {
		defaults: {
			areaPercent: 0.6,
			overlapPercent: 0.3,
			cardRatio: 0.66,
		},
		hoverJumpPercent: 0.25,
		hoverSpreadPercent: 0.4,
		underlayZIndex: -1000,
		layout: {
			cardHeightRatio: 0.2,
			underlayYOffsetRatio: 0.9,
			underlayHeightRatio: 1.45,
			activeUnderlayFillColor: 0xffffff,
			activeUnderlayFillAlpha: 0.35,
			activeUnderlayStrokeColor: 0xffffff,
			activeUnderlayStrokeAlpha: 0.8,
			activeUnderlayStrokeMinWidth: 2,
			activeUnderlayStrokeWidthRatio: 0.035,
			inactiveUnderlayFillColor: 0x000000,
			inactiveUnderlayFillAlpha: 0.25,
		},
	},
	pile: {
		hoverAlpha: 0.8,
		defaultAlpha: 1,
		cardHeightRatio: 0.2,
		cardRatio: 0.66,
	},
	cardPool: {
		initialSize: 120,
	},
	effectCard: {
		renderDurationMs: 2000,
		betweenHandAndCenterRatio: 0.35,
		heightRatio: 0.17,
		cardRatio: 0.66,
	},
} as const;
