CREATE DATABASE IF NOT EXISTS users_data
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE users_data;

CREATE TABLE IF NOT EXISTS users (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	user_id BIGINT UNSIGNED NOT NULL UNIQUE,
	username VARCHAR(255) NOT NULL,
	profile_picture_url VARCHAR(255) NOT NULL,
	card_back_id BIGINT NOT NULL,

	is_active BOOLEAN NOT NULL DEFAULT TRUE,

	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	UNIQUE KEY uq_users_username (username)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS card_gallery (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	user_id BIGINT UNSIGNED NOT NULL,
	img_url VARCHAR(255) NOT NULL,

	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

	CONSTRAINT fk_user_id
		FOREIGN KEY (user_id) REFERENCES users(user_id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS friends (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	requester_id BIGINT UNSIGNED NOT NULL,
	accepter_id  BIGINT UNSIGNED NOT NULL,

	status ENUM('pending', 'accepted', 'rejected', 'blocked')
		NOT NULL DEFAULT 'pending',

	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	CONSTRAINT fk_requester
		FOREIGN KEY (requester_id)
		REFERENCES users(user_id)
		ON DELETE CASCADE,

	CONSTRAINT fk_accepter
		FOREIGN KEY (accepter_id)
		REFERENCES users(user_id)
		ON DELETE CASCADE,

	CONSTRAINT unique_friendship
		UNIQUE (requester_id, accepter_id),

	INDEX idx_requester (requester_id),
	INDEX idx_accepter (accepter_id),

	CHECK (requester_id <> accepter_id)

) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS gamestats (

	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	user_id BIGINT UNSIGNED NOT NULL UNIQUE,

	winrate DECIMAL(5 , 2) DEFAULT 0,
	games_played BIGINT UNSIGNED DEFAULT 0 NOT NULL,
	games_won BIGINT UNSIGNED DEFAULT 0,
	games_lose BIGINT UNSIGNED DEFAULT 0,
	nbr_uno BIGINT UNSIGNED DEFAULT 0,
	nbr_uwu BIGINT UNSIGNED DEFAULT 0,
	nbr_4cards BIGINT UNSIGNED DEFAULT 0,
	nbr_drew BIGINT UNSIGNED DEFAULT 0,
	biggest_hand BIGINT UNSIGNED DEFAULT 0,

	CONSTRAINT fk_user_stats
		FOREIGN KEY (user_id)
		REFERENCES users(user_id)
		ON DELETE CASCADE,

	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

) ENGINE=InnoDB;
