CREATE DATABASE IF NOT EXISTS auth_data
	CHARACTER SET utf8mb4
	COLLATE utf8mb4_unicode_ci;

use auth_data;

CREATE TABLE IF NOT EXISTS credentials (
	ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,

	UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB
