CREATE DATABASE IF NOT EXISTS auth_data
	CHARACTER SET utf8mb4
	COLLATE utf8mb4_unicode_ci;

use auth_data;

CREATE TABLE IF NOT EXISTS credentials (
	ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	username VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,

	UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB

CREATE TABLE IF NOT EXISTS refresh_tokens (
	ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	user_id BIGINT UNSIGNED NOT NULL UNIQUE,
	last_token VARCHAR(255) NULL UNIQUE,
	active_token VARCHAR(255) NOT NULL UNIQUE,

	UNIQUE KEY uq_active_token (active_token)
) ENGINE=InnoDB
